---
- hosts: localhost
  tasks:
  - name: Create User: webdvi
    netapp.ontap.na_ontap_user:
      https: true
      validate_certs: false
      state: present
      name: webdvi
      applications: ssh,console,ontapi,service_processor,http
      authentication_method: password
      lock_user: false
      role_name: admin
      hostname: "{{ netapp_cluster_mgmt_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      set_password: "{{ netapp_webdvi_pass }}"
      vserver: "{{ netapp_cluster_name }}"

  - name: Create User: maintenance
    netapp.ontap.na_ontap_user:
      https: true
      validate_certs: false
      state: present
      name: maintenance
      applications: ssh,console,ontapi,service_processor,http
      authentication_method: password
      lock_user: false
      role_name: admin
      hostname: "{{ netapp_cluster_mgmt_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      set_password: "{{ netapp_maintenance_pass }}"
      vserver: "{{ netapp_cluster_name }}"
