---
- hosts: localhost
  tasks:
  - name: Create User "{{ netapp_new_user }}"
    netapp.ontap.na_ontap_user:
      https: true
      validate_certs: false
      state: present
      applications: ssh,console,ontapi,service_processor,http
      authentication_method: password
      lock_user: false
      role_name: admin
      hostname: "{{ netapp_cluster_mgmt_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      name: "{{ netapp_new_user }}"
      set_password: "{{ netapp_new_user_pass }}"
      vserver: "{{ netapp_vserver }}"
