---
- hosts: localhost
  tasks:
  - name: Add licenses
    na_ontap_license:
      state: present
      hostname: "{{ netapp_cluster_mgmt_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      license_codes: YVUCRRRRYVHXCFABGAAAAAAAAAAA,WKQGSRRRYVHXCFABGAAAAAAAAAAA,SOHOURRRYVHXCFABGAAAAAAAAAAA,YBSOYRRRYVHXCFABGAAAAAAAAAAA,KQSRRRRRYVHXCFABGAAAAAAAAAAA,MBXNQRRRYVHXCFABGAAAAAAAAAAA,QDDSVRRRYVHXCFABGAAAAAAAAAAA,CYAHWRRRYVHXCFABGAAAAAAAAAAA,GUJZTRRRYVHXCFABGAAAAAAAAAAA,OSYVWRRRYVHXCFABGAAAAAAAAAAA,UZLKTRRRYVHXCFABGAAAAAAAAAAA,EJFDVRRRYVHXCFABGAAAAAAAAAAA,MHEYKUNFXMSMUCEZFAAAAAAAAAAA,KWZBMUNFXMSMUCEZFAAAAAAAAAAA,GARJOUNFXMSMUCEZFAAAAAAAAAAA,MNBKSUNFXMSMUCEZFAAAAAAAAAAA,YBCNLUNFXMSMUCEZFAAAAAAAAAAA,ANGJKUNFXMSMUCEZFAAAAAAAAAAA,EPMNPUNFXMSMUCEZFAAAAAAAAAAA,QJKCQUNFXMSMUCEZFAAAAAAAAAAA,UFTUNUNFXMSMUCEZFAAAAAAAAAAA,CEIRQUNFXMSMUCEZFAAAAAAAAAAA,ILVFNUNFXMSMUCEZFAAAAAAAAAAA,SUOYOUNFXMSMUCEZFAAAAAAAAAAA
