---
- hosts: localhost
  tasks:
  - name: Add licenses
    na_ontap_license:
      https: true
      validate_certs: false
      state: present
      hostname: "{{ netapp_cluster_mgmt_ip }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      license_codes: "{{ netapp_licenses }}"
